import bpy
import csv
import os


# Inspired by:
# https://blender.stackexchange.com/questions/274936/is-it-possible-to-export-instances-data-from-spreadsheet-viewer

# Given a selected object with a dependency graph (ex: a Geometry Node), read its transformed vertex data into a file

def _get_filepath(filename):
    """
    Create a filepath for a file that exists in the same directory
    as the current Blender file.
    """
    blend_dir = os.path.dirname(bpy.data.filepath)
    return os.path.join(blend_dir, filename)


def get_depsgraph_points(parent_obj=None, filename="point_data.csv"):
    """
    Given an object with a dependency graph which outputs points,
    read the position of each point.
    :param parent_obj: Object from which we want to read the instance data.
    :param filename: File that will hold the data
    """
    if parent_obj is None:
        parent_obj = bpy.context.active_object
    if not parent_obj:
        print("No object active.")
        return
    #
    data_file_path = _get_filepath(filename)
    #
    m = parent_obj.evaluated_get(bpy.context.evaluated_depsgraph_get()).to_mesh()
    #
    with open(data_file_path, 'w', newline='') as file:
        writer = csv.writer(file)
        for i in range(0, len(m.vertices)):
            v = m.vertices[i].co
            writer.writerow([v[0], v[1], v[2]])


def get_depsgraph_instance_data(parent_obj=None, filename="instance_data.csv",
                                include_position=True, include_rotation=True, include_scale=True, include_header=False):
    """
    Given an object with a dependency graph which outputs instances of an object,
    read data (position, rotation, scale) of each instance.
    :param parent_obj: Object from which we want to read the instance data.
    :param filename: File that will hold the data
    :param include_position: Read position data
    :param include_rotation: Read rotation data
    :param include_scale: Read scale data
    :param include_header: Write what data is included in the file on the first line
    """
    if parent_obj is None:
        parent_obj = bpy.context.active_object
    if not parent_obj:
        print("No object active.")
        return
    # Get the directory of the Blender file
    data_file_path = _get_filepath(filename)
    #
    depsgraph = bpy.context.evaluated_depsgraph_get()
    #
    with open(data_file_path, 'w', newline='') as file:
        writer = csv.writer(file)
        if include_header:
            header = []
            if include_position:
                header.extend(["position_x", "position_y", "position_z"])
            if include_rotation:
                header.extend(["rotation_x", "rotation_y", "rotation_z"])
            if include_scale:
                header.extend(["scale_x", "scale_y", "scale_z"])
            writer.writerow(header)
        #
        for inst in depsgraph.object_instances:
            # Only include instances generated by the selected object
            parent = inst.parent
            if parent is None or parent.original != parent_obj:
                continue
            matrix = inst.matrix_world
            #
            # Extract transform components
            row = []
            if include_position:
                position = matrix.to_translation()
                row.extend([position.x, position.y, position.z])
            if include_rotation:
                rotation = matrix.to_euler()
                row.extend([rotation.x, rotation.y, rotation.z])
            if include_scale:
                scale = matrix.to_scale()
                row.extend([scale.x, scale.y, scale.z])
            # Note that instances will additionally have fields like uv, random_id and others.
            # See Python API for DepsgraphObjectInstance for details.
            # https://docs.blender.org/api/current/bpy.types.DepsgraphObjectInstance.html#bpy.types.DepsgraphObjectInstance
            writer.writerow(row)
